name: xNodusPvP
main: Nodus.Main.Main
version: 3
author: _xNodusPvP_HaskDelicioso
commands:
    hg:
    magma:
    check:
    grandpa:
    setmlg:
    mute:
    desmute:
    stomper:
    endermage:
    viking:
    pvp:
    arenapvp:
    setarena:
    quickdropper:
    airmage:
    autosoup:
    set1v1:
    1v1:
    clicktest:
    subzero:
    setmlg:
    score:
    build:
    setparkour:
    parkour:
    pos2:
    pos1:
    refill:
    thresh:
    Blink:
    tag:
    cs:
    youtuber:
    metheor:
    frozem:
    stats:
    zeus:
    status:
    anchor:
    archer:
    terrorista:
    titan:
    teleporter:
    vampire:
    settexturas:
    texturas:
    ghoul:
    neji:
    shop:
    lag:
    vacuum:
    assasin:
    grandpa:
    avatar:
    dwarf:
    kits2:
    forcefield:
    rain:
    fake:
    tfake:
    classe:
    timelord:
    Pyro:
    infernor:
    chat:
    espadas:
    naruto:
    c4:
    camel:
    fireman:
    madman:
    espada:
    reaper:
    turtle:
    sumo:
    saldo:
    eventomdr:
    eventordm:
    grappler:
    boxer:
    hulk:
    mdr:
    milkman:
    chat:
    head:
    setrdm:
    rdm:
    setmdr:
    ghoul:
    titan:
    confuser:
    darkgod:
    lobisomem:
    fisherman:
    homempedra:
    hunter:
    weaksword:
    critical:
    launcher:
    espada:
    specialist:
    barbarian:
    gm:
    naruto:
    berserker:
    resouper:
    fly:
    s:
    invsee:
    tpall:
    thor:
    gambler:
    skit:
    togglepvp:
    gladiator:
    jellyfish:
    report:
    kangaroo:
    monk:
    ninja:
    granadier:
    ryu:
    poseidon:
    frosty:
    snail:
    build:
    suicide:
    switcher:
    limparchat:
    urgal:
    viper:
    kits:
    copycat:
    fps:
    setfps:
    setmain:
    setchallenge:
    challenge:
    main:
    setspawn:
    spawn:
    resetkit:
    vis:
    invis:
    pao:
    necromancer:
    sonic:
    burstmaster:
    sponger:
    Madman:
    Scorpion:
    Phantom:
    sniper:
    taurus:
    exploder:
    macaco:
    troll:
    trocador:
    vacuum:
    velotrol:
    witherman:
    nofall:
    dj:
    trocador:
    arena:
    broadcast:
    fake:
    tphere:
    ping:
    kick:
    ban:
    bloodgun:
    velotrol:
    deshfire:
    sonic:
    spiderman:
    admin:
    achilles:
    broacast:
    bc:
    s:
    sc:
    kick:
    ban:
    tempban:
    jumper:
    nofall:
    sponger:
    Burstmaster:
    waterchallenge:
    setwaterchallenge:
    deathnote:
    doctor:
    ryu:
    flash:
    rider:
    jutso:
    mlg:
    setmlg:
    drain: