package Nodus.InventariosFake;

import org.bukkit.entity.*;
import org.bukkit.*;
import java.util.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.*;
import org.bukkit.event.inventory.*;
import org.bukkit.event.*;

public class TodosKit implements Listener
{
    public static void guitodos(final Player p) {
        final Inventory inv = Bukkit.getServer().createInventory((InventoryHolder)p, 54, "§cTodos os kits");
        final ItemStack vidro = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        final ItemMeta metav = vidro.getItemMeta();
        metav.setDisplayName("§7Slot");
        vidro.setItemMeta(metav);
        if (!p.hasPermission("kit.jioafjiojfaiofad")) {
            final ItemStack pyro = new ItemStack(Material.STONE_SWORD);
            final ItemMeta metapyro = pyro.getItemMeta();
            metapyro.setDisplayName(ChatColor.AQUA + "PvP");
            final ArrayList descpyro = new ArrayList();
            descpyro.add("§3§l Hab §9§l>> §7Kit sem habilidade");
            metapyro.setLore((List)descpyro);
            pyro.setItemMeta(metapyro);
            inv.addItem(new ItemStack[] { pyro });
        }
        ItemStack pyro = new ItemStack(Material.BOW);
        ItemMeta metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Archer");
        ArrayList descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Mate seus inimigos com seu arco e flecha");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.LAVA);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Fireman");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Nao Tome Dano Da Lava e");
        descpyro.add("§3§l Hab §9§l>> §7Queime Seus Inimigos com sua espada");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.ANVIL);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Anchor");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Nao de knockback e nem leve knockback");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.FIREWORK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Kangaroo");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7De duplos pulos com sua firework");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.MILK_BUCKET);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Milkman");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ganhe Regeneracao, Forca, Velocidade e Resistencia ao Fogo!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.MONSTER_EGG);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Lobisomem");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ganhe velocidade e Super Pulo ao virar um lobisomem!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.NETHER_STAR);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Ninja");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Bata em um jogador aperte shift");
        descpyro.add("§3§l Hab §9§l>> §7para se teleportar ate ele");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SNOW_BLOCK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Frosty");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ganhe forca e Velocidade na Neve");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.REDSTONE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Ghoul");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Se Torne um verdadeiro Ghoul!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.BEDROCK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Titan");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ganhe Regeneracao IV");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.FISHING_ROD);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Fisherman");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Use sua vara de pesca para puxar jogadores");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SPIDER_EYE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Viper");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ao bater em jogadores voce tem 33% de chance");
        descpyro.add("§3§l Hab §9§l>> §7de dar a eles o efeito de Veneno!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.DIAMOND_AXE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Viking");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Cause o dano de uma espada de Iron com seu machado!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.NETHER_FENCE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Infernor");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Crie Uma Arena Infernal!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.WEB);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Snail");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ao bater em jogadores voce tem 33% de chance");
        descpyro.add("§3§l Hab §9§l>> §7de dar a eles o efeito de Lentidao!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.CARROT_STICK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Grandpa");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7KnockBack!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.GOLD_INGOT);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Naruto");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha o poder de virar a Raposa de 9 caldas!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.BOOK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Specialist");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha uma Mesa de Encantos Portatil");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.STATIONARY_WATER);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Jellyfish");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ao clicar no chao coloque uma agua estatica");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.APPLE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Confuser");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Deixe seus inimigos com Confusao");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.DIAMOND_BOOTS);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Stomper");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Esmague seus inimigos");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.PORTAL);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Endermage");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Puxe quem estiver acima ou abaixo de voce!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SNOW_BALL);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Switcher");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ao jogar uma bola de neve em um player");
        descpyro.add("§3§l Hab §9§l>> §7voce sera teleportado ate ele!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.BLAZE_ROD);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Monk");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Coloque items em um local");
        descpyro.add("§3§l Hab §9§l>> §7aleatorio no inventario do inimigo!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SAND);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Camel");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Na areia ganhe velocidade e regenera\u00e7o!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.WATER_BUCKET);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Poseidon");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Quando estiver na neve ganhe forca e speed!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.WOOD_AXE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Thor");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Cause raios como o thor");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.POTION, 1, (short)8265);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Urgal");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ganhe mais forca!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.EMERALD_BLOCK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Sumo");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Lance seus inimigos para o alto");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.ARROW);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Scorpion");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha a flecha do Scorpion");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.IRON_FENCE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Gladiator");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Puxe players para uma arena 1v1!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.BONE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "WeakSword");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Cause efeito de Whiter nos seus inimigos");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.GOLDEN_APPLE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Critical");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha chance de dar golpes criticos nos inimigos");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.OBSIDIAN);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Berserker");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha um monstro de si mesmo!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.STICK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Hunter");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Atire Dardos nos seus inimigos! E os Cause:");
        descpyro.add("§3§l Hab §9§l>> §7Veneno, Confusao, Cegueira e Lentidao");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.LEASH);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Grappler");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Se Pendure Onde Quiser!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.QUARTZ);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Boxer");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tome Dano Reduzido e Cause um Dano imenso com suas luvas!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.DIAMOND);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Hulk");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Levante seus inimigos e os arremesse");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.WOOD_HOE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Reaper");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Com sua enchada deixe seus inmigos com efeito de whiter");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SPONGE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Launcher");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Arremesse seus inimigos para o ar");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.CHAINMAIL_CHESTPLATE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Homem-Pedra");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ganhe Velocidade e Regeneracao na Pedra");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.MUSHROOM_SOUP);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Resouper");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ao matar um jogador ganhe sopas no inventario!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.DIAMOND_CHESTPLATE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Turtle");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ao pressionar SHIFT tome dano reduzido");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.HOPPER);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "DarkGod");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Deixe seus inimigos cegos!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SOUL_SAND);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Thresh");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Puxe as inimiga recalcada!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SIGN);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Outros kits");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Mais kits!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        ItemStack[] arrayOfItemStack;
        for (int descpyro2 = (arrayOfItemStack = inv.getContents()).length, metapyro2 = 0; metapyro2 < descpyro2; ++metapyro2) {
            final ItemStack item = arrayOfItemStack[metapyro2];
            if (item == null) {
                inv.setItem(inv.firstEmpty(), vidro);
            }
        }
        p.openInventory(inv);
    }
    
    @EventHandler
    public void onPlayerCLickInventry(final InventoryClickEvent e) {
        final Player p = (Player)e.getWhoClicked();
        if (e.getInventory().getTitle().equalsIgnoreCase("§cTodos os kits")) {
            e.setCancelled(true);
            if (e.getCurrentItem().getType() == Material.SIGN) {
                e.setCancelled(true);
                p.closeInventory();
                TodosKit2.guitodos(p);
            }
        }
    }
}
