package Nodus.InventariosFake;

import org.bukkit.entity.*;
import org.bukkit.*;
import java.util.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.*;
import org.bukkit.event.inventory.*;
import org.bukkit.event.*;

public class TodosKit2 implements Listener
{
    public static void guitodos(final Player p) {
        final Inventory inv = Bukkit.getServer().createInventory((InventoryHolder)p, 54, "§cTodos os kits 2");
        final ItemStack vidro = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        final ItemMeta metav = vidro.getItemMeta();
        metav.setDisplayName("§7Slot");
        vidro.setItemMeta(metav);
        ItemStack pyro = new ItemStack(Material.ARROW);
        ItemMeta metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Teleporter");
        ArrayList descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Jogue sua Flecha e telporte-se onde ela cair");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.REDSTONE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Assasin");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ao Segurar Shift Ganhe For\u00e7a");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.GOLD_BOOTS);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Dwarf");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Segure shift e carregue seu poder, depois aremesse seus inimigos para longe");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.IRON_BARDING);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Sniper");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Sua sniper e poderosa!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.MELON);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Dj");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Faca um mix de itens!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.COBBLE_WALL);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Trocador");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Troque a armadura!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.ENDER_PEARL);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Jumper");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Domine o poder do teleporte!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.BREAD);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Pao");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7afaste os inimigos com o seu pao!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.STRING);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "SpiderMan");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Atire teias!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.RED_ROSE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Madman");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Deixe os inimigos mais fracos ou roube a resistencia deles!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.TNT);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Exploder");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Atire TnTs!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.WOOD_SWORD);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Achilles");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7O dano de espadas sobre voce e mais fraco!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.BEACON);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Avatar");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Domine os 4 elementos!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.REDSTONE_BLOCK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Deshfire");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Espalhe fogo por perto!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.CHAINMAIL_BOOTS);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "NoFall");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Seja um nofall sem dano de queda!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SKULL_ITEM);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Wither");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Atire cabecas de wither e nao tome dano de explosoes!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SPONGE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Sponger");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha uma esponja portatil! (habilidade stomper)");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.LAPIS_BLOCK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Sonic");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Seus espinhos sao venenosos!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.EYE_OF_ENDER);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Vacuum");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Puxe os inimigos com um buraco negro!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.OBSIDIAN);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Necromancer");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha poderes demoniacos!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.FEATHER);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Phantom");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha a habilidade de voar!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.EMERALD_BLOCK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Taurus");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Lance quem estiver por perto para cima!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.MINECART);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Velotrol");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7De um boost e exploda seus inimigos!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.WOOD_HOE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Bloodgun");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha uma arma de sangue!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.NETHER_FENCE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "ForceField");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Hask OpenGL!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.GOLD_HOE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Burstmaster");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Atire balas explosivas, §4ALLAHU AKBAR!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SLIME_BALL);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Doctor");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Cure-se de qualquer efeito");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.BOOK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "DeathNote");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Escreva o nome de seus inimigos no deathnote");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.REDSTONE_TORCH_ON);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Flash");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Teleporte-se em um Flash!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.DIAMOND_BLOCK);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Ryu");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Hadouken!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SADDLE);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Rider");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha um cavalin portatil(§5Qnt futurismo).");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.PAPER);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Jutso");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Jutso de substituicao!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.GHAST_TEAR);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Rain");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Fassa flechas perseguirem seu inimigo ehauehu!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.NETHER_STAR);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Drain");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Ao matar alguem sua vida dobra para 20 coracoes!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.WATCH);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "TimeLord");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Congele quem estiver ao redor!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.STONE_BUTTON);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "C4");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Exploda os inimigos com uma bomba!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.MAGMA_CREAM);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Magma");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Tenha chance de colocar fogo nos inimigos!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.WOOL);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "AirMage");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Fa\u00e7a os inimigos levitar!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.SUGAR);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Zeus");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Jogue raios!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.DIAMOND_SWORD);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Barbarian");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Evolua sua espada a cada Kill");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.FIREBALL);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Pyro");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Lance bolas de fogo!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.getMaterial(289));
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Terrorista");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Caia e provoque explosoes!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        pyro = new ItemStack(Material.BLAZE_ROD);
        metapyro = pyro.getItemMeta();
        metapyro.setDisplayName(ChatColor.AQUA + "Macaco");
        descpyro = new ArrayList();
        descpyro.add("§3§l Hab §9§l>> §7Escale qualquer coisa defendendo com sua espada! e nao tome dano de queda!");
        metapyro.setLore((List)descpyro);
        pyro.setItemMeta(metapyro);
        inv.addItem(new ItemStack[] { pyro });
        ItemStack[] arrayOfItemStack;
        for (int descpyro2 = (arrayOfItemStack = inv.getContents()).length, metapyro2 = 0; metapyro2 < descpyro2; ++metapyro2) {
            final ItemStack item = arrayOfItemStack[metapyro2];
            if (item == null) {
                inv.setItem(inv.firstEmpty(), vidro);
            }
        }
        p.openInventory(inv);
    }
    
    @EventHandler
    public void onPlayerCLickInventry(final InventoryClickEvent e) {
        final Player p = (Player)e.getWhoClicked();
        if (e.getInventory().getTitle().equalsIgnoreCase("§cTodos os kits 2")) {
            e.setCancelled(true);
        }
    }
}
